spring.application.name=newsFinder

spring.datasource.url=jdbc:h2:file:./data/newsdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.datasource.username=sa
spring.datasource.password=

voyage.api-key=${VOYAGE_API_KEY}